name: Simple Workflow

on:
  #schedule:
  #- cron: "0 * * * *"
  workflow_dispatch:

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Display 1st msg
        run: echo "Récupération du code source"
        
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: Display 2nd msg
        run: echo "Vérification terminé"
